[2022-06-19 19:45:33,961] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-19T19:45:31.328447+00:00 [queued]>
[2022-06-19 19:45:33,973] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-19T19:45:31.328447+00:00 [queued]>
[2022-06-19 19:45:33,973] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 19:45:33,973] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-19 19:45:33,973] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 19:45:33,988] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): csv_to_database> on 2022-06-19 19:45:31.328447+00:00
[2022-06-19 19:45:33,992] {standard_task_runner.py:52} INFO - Started process 73 to run task
[2022-06-19 19:45:33,995] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'T-dbt-job-cdc_load', 'csv_to_database', 'manual__2022-06-19T19:45:31.328447+00:00', '--job-id', '8', '--raw', '--subdir', 'DAGS_FOLDER/docker_job/dbt_test.py', '--cfg-path', '/tmp/tmpz_pna_w9', '--error-file', '/tmp/tmp80y7qe7_']
[2022-06-19 19:45:33,995] {standard_task_runner.py:80} INFO - Job 8: Subtask csv_to_database
[2022-06-19 19:45:34,042] {task_command.py:370} INFO - Running <TaskInstance: T-dbt-job-cdc_load.csv_to_database manual__2022-06-19T19:45:31.328447+00:00 [running]> on host 7cbff6e51e2a
[2022-06-19 19:45:34,101] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=samuelolle@yahoo.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=T-dbt-job-cdc_load
AIRFLOW_CTX_TASK_ID=csv_to_database
AIRFLOW_CTX_EXECUTION_DATE=2022-06-19T19:45:31.328447+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-19T19:45:31.328447+00:00
[2022-06-19 19:45:34,109] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-19 19:45:34,112] {postgres.py:127} INFO - Running copy expert: COPY analytics_stage.users_cdc FROM STDIN, filename: /opt/airflow/dags/docker_job/data/users.csv
[2022-06-19 19:45:34,117] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-19 19:45:34,127] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-19 19:45:34,129] {postgres.py:127} INFO - Running copy expert: COPY analytics_stage.walls_cdc FROM STDIN, filename: /opt/airflow/dags/docker_job/data/walls.csv
[2022-06-19 19:45:34,134] {base.py:68} INFO - Using connection ID '***' for task execution.
[2022-06-19 19:45:34,138] {python.py:173} INFO - Done. Returned value was: None
[2022-06-19 19:45:34,151] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=T-dbt-job-cdc_load, task_id=csv_to_database, execution_date=20220619T194531, start_date=20220619T194533, end_date=20220619T194534
[2022-06-19 19:45:34,167] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-19 19:45:34,195] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
